import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowUpRight } from "lucide-react";
import { Logo } from "./components";
const concepts = [
 {name:"Decision in Motion", path:"/decision-in-motion", code:"A", thesis:"Make an invisible decision system tangible through a live operational moment.", strength:"Most concrete product demonstration", risk:"The product may initially feel workflow-specific", cls:"motion", preview:<><span className="miniRequest">Request arrives</span><i/><span className="miniDecision">Context assembled<br/><b>Exception recommended</b></span></>},
 {name:"Invisible Business", path:"/invisible-business", code:"B", thesis:"Expose the hidden layer of accumulated judgment that actually runs a small business.", strength:"Strongest category-defining story", risk:"More conceptual before the product reveal", cls:"invisible", preview:<><strong>The part of your business<br/>software can’t see.</strong><div className="miniOrbit">RULES · PROMISES · HISTORY</div></>},
 {name:"Decision Traces", path:"/decision-traces", code:"C", thesis:"Position decision traces as a new primitive that turns judgment into durable infrastructure.", strength:"Strongest technical differentiation", risk:"Requires learning a new product concept", cls:"traces", preview:<><div className="miniTrace"><small>TRIGGER</small><b>Patient request</b></div><em>→</em><div className="miniTrace"><small>EVIDENCE</small><b>Prior promise</b></div><em>→</em><div className="miniTrace"><small>ACTION</small><b>Exception</b></div></>}
];
export default async function Home({searchParams}:{searchParams:Promise<{review?:string}>}) { const q=await searchParams; if(q.review!=="true") redirect("/decision-in-motion"); return <main className="hub"><header><Logo/><span>Concept review · GPTMinds</span></header><section className="hubIntro"><p>THREE STRATEGIC DIRECTIONS</p><h1>One product.<br/><i>Three ways in.</i></h1><div>Each concept makes a different case for the same company: a decision engine that learns how a small business actually works.</div></section><section className="conceptGrid">{concepts.map(c=><article className={`concept ${c.cls}`} key={c.code}><div className="conceptMeta"><span>{c.code}</span><small>VARIANT {c.code}</small></div><div className="conceptPreview">{c.preview}</div><h2>{c.name}</h2><p>{c.thesis}</p><Link href={c.path}>Open concept <ArrowUpRight size={18}/></Link><aside><div><small>MAIN STRENGTH</small>{c.strength}</div><div><small>MAIN RISK</small>{c.risk}</div><div><small>EVALUATE</small>Problem clarity · Credibility · Category potential · Memorability</div></aside></article>)}</section><footer>Prepared for focused review <span>·</span> No direction is presented as the winner</footer></main> }
